# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bcms_xml_data_feeds}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["AgoraGames"]
  s.date = %q{2010-01-19}
  s.description = %q{A BrowserCMS module which fetches, caches and displays arbitrary XML feeds. Based on http://github.com/jonleighton/bcms_feeds by j@jonathanleighton.com}
  s.email = %q{github@agoragames.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "app/controllers/application_controller.rb",
     "app/controllers/cms/xml_data_feeds_controller.rb",
     "app/helpers/application_helper.rb",
     "app/models/xml_data_feed.rb",
     "app/portlets/xml_data_feed_portlet.rb",
     "app/views/cms/xml_data_feeds/_form.html.erb",
     "app/views/cms/xml_data_feeds/render.html.erb",
     "app/views/portlets/xml_data_feed/_form.html.erb",
     "app/views/portlets/xml_data_feed/render.html.erb",
     "db/migrate/20100118155849_create_xml_data_feeds.rb",
     "db/migrate/20100118205655_add_xml_data_feed_expires_at_and_etag.rb",
     "lib/bcms_xml_data_feeds.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/agoragames/bcms_xml_data_feed}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{XML Data Feeds in BrowserCMS}
  s.test_files = [
    "test/functional/cms/xml_data_feeds_controller_test.rb",
     "test/performance/browsing_test.rb",
     "test/test_helper.rb",
     "test/unit/models/xml_data_feed_test.rb",
     "test/unit/portlets/xml_data_feed_portlet_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
    else
      s.add_dependency(%q<xml-simple>, [">= 0"])
    end
  else
    s.add_dependency(%q<xml-simple>, [">= 0"])
  end
end

